-- =====================================================================
-- Schema legacy del sistema de la empresa de subastas (provisto por los
-- profes en EstructuraActual.sql, originalmente SQL Server / T-SQL).
--
-- Esta versión está adaptada a H2 / dialecto PostgreSQL para que se pueda
-- ejecutar en el dev local. Mantiene los mismos nombres de tablas y FKs.
-- Cambios respecto al original:
--   • SQL Server `int identity`        → `bigint generated by default as identity primary key`
--   • SQL Server `varbinary(max)`      → `blob`
--   • SQL Server `getdate()`           → `current_date`
--   • SQL Server `dateAdd(dd, 10, …)`  → `dateadd('day', 10, …)`
--   • Se sacaron los `go` (T-SQL only)
--   • Typos del original corregidos (ver al pie del archivo)
-- =====================================================================

CREATE TABLE paises (
    numero          INT NOT NULL,
    nombre          VARCHAR(250) NOT NULL,
    nombreCorto     VARCHAR(250) NULL,
    capital         VARCHAR(250) NOT NULL,
    nacionalidad    VARCHAR(250) NOT NULL,
    idiomas         VARCHAR(150) NOT NULL,
    CONSTRAINT pk_paises PRIMARY KEY (numero)
);

CREATE TABLE personas (
    identificador   INT NOT NULL AUTO_INCREMENT,
    documento       VARCHAR(20) NOT NULL,
    nombre          VARCHAR(150) NOT NULL,
    direccion       VARCHAR(250),
    estado          VARCHAR(15) CHECK (estado IN ('activo', 'inactivo')),
    foto            BLOB,
    CONSTRAINT pk_personas PRIMARY KEY (identificador)
);

CREATE TABLE empleados (
    identificador   INT NOT NULL,
    cargo           VARCHAR(100),
    sector          INT NULL,
    CONSTRAINT pk_empleados PRIMARY KEY (identificador),
    CONSTRAINT fk_empleados_personas FOREIGN KEY (identificador) REFERENCES personas(identificador)
);

CREATE TABLE sectores (
    identificador       INT NOT NULL AUTO_INCREMENT,
    nombreSector        VARCHAR(150) NOT NULL,
    codigoSector        VARCHAR(10) NULL,
    responsableSector   INT NULL,
    CONSTRAINT pk_sectores PRIMARY KEY (identificador),
    CONSTRAINT fk_sectores_empleados FOREIGN KEY (responsableSector) REFERENCES empleados(identificador)
);

CREATE TABLE seguros (
    nroPoliza        VARCHAR(30) NOT NULL,
    compania         VARCHAR(150) NOT NULL,
    polizaCombinada  VARCHAR(2) CHECK (polizaCombinada IN ('si','no')),
    importe          DECIMAL(18,2) NOT NULL CHECK (importe > 0),
    CONSTRAINT pk_seguro PRIMARY KEY (nroPoliza)
);

CREATE TABLE clientes (
    identificador   INT NOT NULL,
    numeroPais      INT,
    admitido        VARCHAR(2) CHECK (admitido IN ('si','no')),
    categoria       VARCHAR(10) CHECK (categoria IN ('comun', 'especial', 'plata', 'oro', 'platino')),
    verificador     INT NOT NULL,
    CONSTRAINT pk_clientes PRIMARY KEY (identificador),
    CONSTRAINT fk_clientes_personas  FOREIGN KEY (identificador) REFERENCES personas(identificador),
    CONSTRAINT fk_clientes_empleados FOREIGN KEY (verificador)   REFERENCES empleados(identificador),
    CONSTRAINT fk_clientes_paises    FOREIGN KEY (numeroPais)    REFERENCES paises(numero)
);

CREATE TABLE duenios (
    identificador           INT NOT NULL,
    numeroPais              INT,
    verificacionFinanciera  VARCHAR(2) CHECK (verificacionFinanciera IN ('si','no')),
    verificacionJudicial    VARCHAR(2) CHECK (verificacionJudicial   IN ('si','no')),
    calificacionRiesgo      INT CHECK (calificacionRiesgo IN (1,2,3,4,5,6)),
    verificador             INT NOT NULL,
    CONSTRAINT pk_duenios PRIMARY KEY (identificador),
    CONSTRAINT fk_duenios_personas  FOREIGN KEY (identificador) REFERENCES personas(identificador),
    CONSTRAINT fk_duenios_empleados FOREIGN KEY (verificador)   REFERENCES empleados(identificador)
);

CREATE TABLE subastadores (
    identificador   INT NOT NULL,
    matricula       VARCHAR(15),
    region          VARCHAR(50),
    CONSTRAINT pk_subastadores PRIMARY KEY (identificador),
    CONSTRAINT fk_subastadores_personas FOREIGN KEY (identificador) REFERENCES personas(identificador)
);

CREATE TABLE subastas_legacy (
    identificador        INT NOT NULL AUTO_INCREMENT,
    -- las subastas tienen al menos 10 días de anticipación al momento de crearlas
    fecha                DATE CHECK (fecha > DATEADD('day', 10, CURRENT_DATE)),
    hora                 TIME NOT NULL,
    estado               VARCHAR(10) CHECK (estado IN ('abierta','cerrada')),
    subastador           INT NULL,
    -- dirección donde se desarrolla el evento
    ubicacion            VARCHAR(350) NULL,
    capacidadAsistentes  INT NULL,
    -- características del lugar donde se hacen las subastas
    tieneDeposito        VARCHAR(2) CHECK (tieneDeposito   IN ('si','no')),
    seguridadPropia      VARCHAR(2) CHECK (seguridadPropia IN ('si','no')),
    categoria            VARCHAR(10) CHECK (categoria IN ('comun', 'especial', 'plata', 'oro', 'platino')),
    CONSTRAINT pk_subastas_legacy PRIMARY KEY (identificador),
    CONSTRAINT fk_subastas_legacy_subastadores FOREIGN KEY (subastador) REFERENCES subastadores(identificador)
);

CREATE TABLE productos (
    identificador           INT NOT NULL AUTO_INCREMENT,
    fecha                   DATE,
    disponible              VARCHAR(2) CHECK (disponible IN ('si','no')),
    -- se obtiene después de que un empleado realiza la revisión
    descripcionCatalogo     VARCHAR(500) NULL DEFAULT 'No Posee',
    -- URL que apunta a un PDF firmado con la descripción del producto
    descripcionCompleta     VARCHAR(300) NOT NULL,
    revisor                 INT NOT NULL,
    duenio                  INT NOT NULL,
    seguro                  VARCHAR(30) NULL,
    CONSTRAINT pk_productos PRIMARY KEY (identificador),
    CONSTRAINT fk_productos_empleados FOREIGN KEY (revisor) REFERENCES empleados(identificador),
    CONSTRAINT fk_productos_duenios   FOREIGN KEY (duenio)  REFERENCES duenios(identificador),
    CONSTRAINT fk_productos_seguros   FOREIGN KEY (seguro)  REFERENCES seguros(nroPoliza)
);

CREATE TABLE fotos (
    identificador   INT NOT NULL AUTO_INCREMENT,
    producto        INT NOT NULL,
    foto            BLOB NOT NULL,
    CONSTRAINT pk_fotos PRIMARY KEY (identificador),
    CONSTRAINT fk_fotos_productos FOREIGN KEY (producto) REFERENCES productos(identificador)
);

CREATE TABLE catalogos (
    identificador   INT NOT NULL AUTO_INCREMENT,
    descripcion     VARCHAR(250) NOT NULL,
    subasta         INT NULL,
    responsable     INT NOT NULL,
    CONSTRAINT pk_catalogos PRIMARY KEY (identificador),
    CONSTRAINT fk_catalogos_empleados FOREIGN KEY (responsable) REFERENCES empleados(identificador),
    CONSTRAINT fk_catalogos_subastas  FOREIGN KEY (subasta)     REFERENCES subastas_legacy(identificador)
);

CREATE TABLE itemsCatalogo (
    identificador   INT NOT NULL AUTO_INCREMENT,
    catalogo        INT NOT NULL,
    producto        INT NOT NULL,
    precioBase      DECIMAL(18,2) NOT NULL CHECK (precioBase > 0.01),
    comision        DECIMAL(18,2) NOT NULL CHECK (comision   > 0.01),
    subastado       VARCHAR(2) CHECK (subastado IN ('si','no')),
    CONSTRAINT pk_itemsCatalogo PRIMARY KEY (identificador),
    CONSTRAINT fk_itemsCatalogo_catalogos FOREIGN KEY (catalogo) REFERENCES catalogos(identificador),
    CONSTRAINT fk_itemsCatalogo_productos FOREIGN KEY (producto) REFERENCES productos(identificador)
);

CREATE TABLE asistentes (
    identificador   INT NOT NULL AUTO_INCREMENT,
    numeroPostor    INT NOT NULL,
    cliente         INT NOT NULL,
    subasta         INT NOT NULL,
    CONSTRAINT pk_asistentes PRIMARY KEY (identificador),
    CONSTRAINT fk_asistentes_clientes FOREIGN KEY (cliente) REFERENCES clientes(identificador),
    CONSTRAINT fk_asistentes_subasta  FOREIGN KEY (subasta) REFERENCES subastas_legacy(identificador)
);

CREATE TABLE pujos (
    identificador   INT NOT NULL AUTO_INCREMENT,
    asistente       INT NOT NULL,
    item            INT NOT NULL,
    importe         DECIMAL(18,2) NOT NULL CHECK (importe > 0.01),
    ganador         VARCHAR(2) DEFAULT 'no' CHECK (ganador IN ('si','no')),
    CONSTRAINT pk_pujos PRIMARY KEY (identificador),
    CONSTRAINT fk_pujos_asistentes    FOREIGN KEY (asistente) REFERENCES asistentes(identificador),
    CONSTRAINT fk_pujos_itemsCatalogo FOREIGN KEY (item)      REFERENCES itemsCatalogo(identificador)
);

CREATE TABLE registroDeSubasta (
    identificador   INT NOT NULL AUTO_INCREMENT,
    subasta         INT NOT NULL,
    duenio          INT NOT NULL,
    producto        INT NOT NULL,
    cliente         INT NOT NULL,
    importe         DECIMAL(18,2) NOT NULL CHECK (importe  > 0.01),
    comision        DECIMAL(18,2) NOT NULL CHECK (comision > 0.01),
    CONSTRAINT pk_registroDeSubasta PRIMARY KEY (identificador),
    CONSTRAINT fk_registroDeSubasta_subastas  FOREIGN KEY (subasta)  REFERENCES subastas_legacy(identificador),
    CONSTRAINT fk_registroDeSubasta_duenios   FOREIGN KEY (duenio)   REFERENCES duenios(identificador),
    CONSTRAINT fk_registroDeSubasta_producto  FOREIGN KEY (producto) REFERENCES productos(identificador),
    CONSTRAINT fk_registroDeSubasta_cliente   FOREIGN KEY (cliente)  REFERENCES clientes(identificador)
);

-- =====================================================================
-- Typos detectados en el original (EstructuraActual.sql) y corregidos:
--   • personas.estado:               'incativo'  → 'inactivo'
--   • subastas.estado:               'carrada'   → 'cerrada'
--   • duenios.verificaci�nFinanciera → verificacionFinanciera (encoding roto)
--   • duenios.verificaci�nJudicial   → verificacionJudicial   (encoding roto)
--   • seguros.nroPoliza:             "varchar(30) not null." → "VARCHAR(30) NOT NULL,"
--   • clientes.fk_clientes_personas faltaba paréntesis explícito
--   • Faltaban varias comas finales en columnas previas a CONSTRAINT
--   • La tabla `subastas` se renombró a `subastas_legacy` para no
--     colisionar con la tabla `subastas` que genera Hibernate (modelo
--     interno del backend). Si se quiere unificar, habría que migrar
--     el modelo Java al schema legacy.
-- =====================================================================
